### ISSUE TITLE
create search plugin for web browsers

### ISSUE THREAD

**Issue by iman-salmani** [Targoman/targomanWUI#1]
hello and thank of targoman team
please create a web browsers search plugins for better use of targoman.

**Comment by ziabary** [comment]
Hi and thanks for your feedback you can use [Tarjomak](https://mimalef70.github.io/tarjomak/) plugin on most browsers. Also you can install [Android App](https://play.google.com/store/apps/details?id=com.anonycoders.targoman&hl=en)
