### ISSUE TITLE
Failed to fetch

### ISSUE THREAD

**Issue by Rahjooyan** [Targoman/targomanWUI#4]
سلام. چند مسئله است لطفا بررسی کنید:
1. ابتدای خطای زیر حین ترجمه است. 
"Failed to fetch"
2. مشکل بعدی حذف متن ترجمه شده بعد از روگرفت آن است. گاهی ترجمه نیاز به بررسی مجدد دارد که پاک شدن آن مشکل‌ساز است. شاید بدلایلی مثلا شلوغی منابع توجیه شود ولی تجربه کاربری ناخوشایندی برای کاربر نهایی ایجاد می‌کند. 
3. بهتر می‌بود دکمه حذف متن اصلی مشابه سرویس‌های دیگر در حد فاصل متن اصلی و ترجمه قرار می‌گرفت.مثلا ترجمه گوگل در نسخه فارسی در سمت چپ و در نسخه انگلیسی سمت راست متن اصلی قرار دارد. در یاندکس، بایدو و بینگ هم همین موقعیت را دارند.
به امید پیشرفت‌های بعدی.

**Comment by ziabary** [comment]
با سپاس در خصوص اعلام مشکلات: 
۱- خطا ناشی از کش بود برطرف شد 
۲- مشکل به دلیل تغییر آدرس رخ می‌داد برطرف شد 
۳- با توجه به اینکه انتقال دکمه حذف به بالا موجب کوچک‌شدن باکس ورود متن می‌شود (مشکلی که در گوگل هم وجود دارد) در نتیجه تغییر داده نشد
